### ISSUE TITLE
isue with version

### ISSUE THREAD

**Issue by Angelinas1** [jeroenpardon/repository.jeroen#1]
U use 3 diferent version number...
Set one unic version for start
Now is this:
in zip file 0.0.1
in zip file addon.xml version="1.0.1
in addon version="2.0.1

Remove

```
	<requires>
		<import addon="xbmc.addon" version="12.0.0"/>
</requires>
```

This is only for krypton version...need to be open for all version.

**Comment by jeroenpardon** [comment]
Thanks, all versions are the same now but I'm still getting the error unfortunately

**Comment by Angelinas1** [comment]
I am on leia , and after removing wrong file from ..Roaming\Kodi\addons\temp\ ,all working.
With removing remove requires

**Comment by jeroenpardon** [comment]
After removing <requires> the zip fails to install. But even with <requires> added and removing the temp folder still the same error

**Comment by jeroenpardon** [comment]
It is getting enabled for me too, but when actually opening the repo in the addon browser I get the could not connect error

**Comment by Angelinas1** [comment]
Working for me I downgrade addon watchlist to version="0.0.1"
And I have ugrade from 2 repo...kodi and your.
-I chose your, and update without error
Watchlist want show in your repo when open from Addon browser....

**Comment by jeroenpardon** [comment]
Finally!

That worked for me too at last.. I still don't understand it because it watchlist really is v 0.0.2...

At least it works, hopefully I can add the rest without issues. Thanks so much for your help, I was ready to give up 👍
